attention_head_size: 1
categorical_groups: {}
dropout: 0.1
embedding_labels:
  group:
    group: 0
embedding_paddings: []
embedding_sizes:
  group: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 24
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADEyMTQ3NDYyNHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADEyMTQ3NDYy
      NHEBYS4BAAAAAAAAAEw3l0A=
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  eps: 1.0e-08
  method: standard
  scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADEwNDI0MTAwOHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADEwNDI0MTAw
      OHEBYS4BAAAAAAAAACNkIz4=
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
share_single_variable_networks: false
static_categoricals:
- group
static_reals:
- encoder_length
- open_center
- open_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
weight_decay: 0.0
x_categoricals:
- group
x_reals:
- encoder_length
- open_center
- open_scale
- relative_time_idx
